name: RSpec

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ '3.4.5', '3.4', '3.3', '3.2', '3.1' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Dependencies
        run: bundle install -j 4
      - name: Run Specs
        run: bundle exec rspec --format progress -p 1
